### ISSUE TITLE
Migrar o banco de dados online para uma conta relacionada ao aplicativo

### ISSUE THREAD

**Issue by Ronyell** [jbb-mobile/2016.2-Jardim-Botanico-Mobile#11]

**Comment by mateusmanuel** [comment]
Para não atrapalhar o desenvolvimento do aplicativo, foi fixado que se compilado em modo de debug ele requisite da url atual, se em modo de release, ou seja, para que se publique na Play Store, é utilizado a url do servidor proprio do jbb.
